# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='peply',
            new_name='reply',
        ),
        migrations.AddField(
            model_name='reply',
            name='thread',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.Thread', verbose_name='Tópico'),
            preserve_default=False,
        ),
    ]
